name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: lscgit 웹서버 배포중
          uses: appleboy/ssh-action@master
          with: 
            host: ${{ 218.145.31.160 }} 
            username: ${{ pshgit }} 
            password: ${{ pshgit }}
            script: 'cd /home/pshgit/html && git pull'    
